const nodemailer = require('nodemailer');
require('dotenv').config();

const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.resend.com',
    port: parseInt(process.env.SMTP_PORT || '465'),
    secure: process.env.SMTP_PORT === '465',
    auth: {
        user: process.env.SMTP_USER || 'resend',
        pass: process.env.RESEND_API_KEY || 'dummy_key',
    },
});

async function dispatchPaymentReminder({ toEmail, clientName, amountDue, invoiceNumber, dueDate }) {
    const mailOptions = {
        from: process.env.RESEND_FROM_EMAIL || 'support@srdgintel.com',
        to: toEmail,
        subject: `Payment Notice: Invoice #${invoiceNumber || '0000'}`,
        html: `
            <div style="font-family: 'Syne', system-ui, sans-serif; max-width: 550px; margin: 0 auto; background-color: #0a0a0a; color: #f4f4f5; padding: 35px; border-radius: 12px; border: 1px solid #27272a; box-shadow: 0 10px 25px rgba(0,0,0,0.5);">
                
                <div style="text-align: center; margin-bottom: 25px;">
                    <img src="https://i.postimg.cc/9FhB2btn/Trades-Pay-AI-logo-png.jpg" alt="TradesPay AI Logo" style="max-width: 180px; height: auto;">
                </div>
                
                <h2 style="color: #ff5c1a; text-align: center; margin-top: 0; font-family: 'Bebas Neue', Impact, sans-serif; letter-spacing: 1.5px; font-size: 26px; text-transform: uppercase;">
                    Automated Payment Reminder
                </h2>
                
                <p style="font-size: 16px; color: #e4e4e7; line-height: 1.5;">Hello ${clientName},</p>
                <p style="font-size: 16px; color: #e4e4e7; line-height: 1.5;">This is a friendly automated notice from our system regarding an outstanding balance on your account. Invoice <strong style="color: #ff5c1a;">#${invoiceNumber}</strong> requires your attention.</p>
                
                <div style="background-color: #18181b; padding: 20px; border-radius: 8px; margin: 30px 0; border-left: 4px solid #ff5c1a;">
                    <p style="margin: 0 0 10px 0; font-size: 20px;"><strong>Total Due:</strong> <span style="color: #ff5c1a; font-weight: bold;">${amountDue}</span></p>
                    <p style="margin: 0; font-size: 16px; color: #a1a1aa;"><strong>Due Date:</strong> ${dueDate || 'Due upon receipt'}</p>
                </div>
                
                <div style="text-align: center; margin-top: 35px; margin-bottom: 20px;">
                    <a href="#" style="display: inline-block; background-color: #ff5c1a; color: #ffffff; padding: 16px 32px; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 16px; text-transform: uppercase; letter-spacing: 1px;">Settle Invoice Now</a>
                </div>
                
                <div style="margin-top: 45px; border-top: 1px solid #27272a; padding-top: 25px; text-align: center;">
                    <p style="color: #71717a; font-size: 13px; margin: 0 0 8px 0;">This communication was automatically generated by TradesPay AI.</p>
                    <p style="color: #d4d4d8; font-size: 12px; margin: 0; font-weight: 800; letter-spacing: 2px;">POWERED BY SRDGINTEL</p>
                </div>
            </div>`
    };
    return await transporter.sendMail(mailOptions);
}

module.exports = { dispatchPaymentReminder };